### ISSUE TITLE
Failed to load the extension "megasearch

### ISSUE THREAD

**Issue by bunnywaffle** [atxcowboy/megasearch#2]
When I  enable it and restart the webUI, it gives me this error.

Traceback (most recent call last):
  File "G:\LangAI\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "G:\LangAI\oobabooga_windows\text-generation-webui\extensions\megasearch\script.py", line 38, in <module>
    from summarizer import Summarizer
ModuleNotFoundError: No module named 'summarizer'

![image](https://github.com/atxcowboy/megasearch/assets/100540808/d4f806b1-abac-4dbe-970d-6980596e2479)

**Comment by atxcowboy** [comment]
Then thing I dislike most about python is the missing requirements.txt in most projects and of course, I forgot to add it to my own first project too!

I have now added a requirements.txt.

Please try
`pip install -r requirements.txt`

or

```
pip install beautifulsoup4
pip install bert-extractive-summarizer
pip install spacy
python -m spacy download en_core_web_sm
```

**Comment by bunnywaffle** [comment]
I don't know why, but I am still getting this error:

ERROR:Failed to load the extension "megasearch".Traceback (most recent call last):  File "G:\LangAI\oobabooga_windows\text-generation-webui\modules\extensions.py", line 34, in load_extensions    exec(f"import extensions.{name}.script")  File "<string>", line 1, in <module>  File "G:\LangAI\oobabooga_windows\text-generation-webui\extensions\megasearch\script.py", line 38, in <module>    from summarizer import SummarizerModuleNotFoundError: No module named 'summarizer'
